//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZebPayCurrencyConverter
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CurrencyConverterEntities : DbContext
    {
        public CurrencyConverterEntities()
            : base("name=CurrencyConverterEntities")
        {
            Database.Connection.ConnectionString = "data source=lfva89oyqr.database.windows.net;initial catalog=CurrencyConverter;persist security info=True;user id=tejassa;password=bcs@1234;MultipleActiveResultSets=True;App=EntityFramework"; 
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ssz_country> ssz_country { get; set; }
        public virtual DbSet<ssz_error_log> ssz_error_log { get; set; }
        public virtual DbSet<ssz_exchange_rate> ssz_exchange_rate { get; set; }
    }
}
