//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZebPayCurrencyConverter
{
    using System;
    using System.Collections.Generic;
    
    public partial class ssz_error_log
    {
        public int error_log_id { get; set; }
        public string controller_name { get; set; }
        public string page_api_name { get; set; }
        public string action_Name { get; set; }
        public string error_msg { get; set; }
        public Nullable<System.DateTime> date_of_occurence { get; set; }
    }
}
